[package]
name = "github-wiki-see"
version = "0.2.1"
authors = ["Nelson Chen <crazysim@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Who knows.
nipper = "0.1.9"
# WIP!
rocket = "0.5.0-rc.1"
# WIP
askama = { git = "https://github.com/djc/askama.git", features = ["with-rocket", "mime", "mime_guess"], rev="4d936524" }
askama_rocket = { git = "https://github.com/djc/askama.git", rev="4d936524" }
reqwest = { version = "0.11", features = ["deflate", "brotli", "gzip"] }
tokio = { version = "1", features = ["full"] }
comrak = "0.12.1"
regex = "1.5.4"
lazy_static = "1.4.0"
percent-encoding = "2.1.0"
scraper = "0.12.0"
quick-xml = "0.22.0"
phf = { version = "0.10", features = ["macros"] }

[features]
